version: '3.8'

services:
  log-system:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - log-data:/app/backend/data
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  log-data:
